import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "Done...!": "نجاح",
          "Parking has been booked": "تم حجز الموقف",
          "Ticket Expired": "التذكرة منتهية",
          "Your Ticket": "تذكرتك",
          "is Expired": "منتهية",
          "BOOK A PARKING": "حجز موقف",
          "EMIRATE": "إمارة",
          "zone code": "رمز المنطقة",
          "zone number": "رقم المنطقة",
          "Duration": "المدة",
          "end": "نهاية",
          "Parking timings in selected zone is 8:00 AM to 10:00 PM,(Sat - Thu). Free parking on fridays and public holidays (maximum time allowed is 4 hours)":
              "أوقات الوقوف في المنطقة المحددة من 8:00 صباحًا إلى 10:00 مساءً (السبت - الخميس). الوقوف مجاني أيام الجمعة والعطلات الرسمية (الحد الأقصى للوقت المسموح به هو 4 ساعات)",
          "book through sms": "الحجز عبر الرسائل النصية",
          "cancel": "إلغاء",
          "Choose SIM for this SMS": "اختر الشريحة لهذه الرسالة",
          "Re-Book Parking": "إعادة حجز الموقف",
          "emirate": "إمارة",
          "hour(s) used": "ساعة/ساعات مستخدمة",
          "date/time": "التاريخ/الوقت",
          "Hr": "سا",
          "PM": "م",
          "re-book": "إعادة الحجز",
          "Cancel": "إلغاء",
          "Reminder has been added": "تم إضافة التذكير",
          "Parking Expired": "الموقف منتهٍ",
          "Your Parking": "موقفك",
          "PARKING REMINDER": "تذكير بالموقف",
          "remind me on": "ذكرني في",
          "remind me before": "ذكرني قبل",
          "add reminder": "إضافة تذكير",
          "full name": "الاسم الكامل",
          "email": "البريد الإلكتروني",
          "message": "الرسالة",
          "Send": "إرسال",
          "Reservation": "الحجز",
          " AM": " ص",
          " PM": " م",
          "amount": "المبلغ",
          " aed": " د.أ",
          "parking history": "سجل المواقف",
          "Book A Parking": "حجز موقف",
          "remind ticket": "تذكير بالتذكرة",
          "AM": "ص",
          "expires at": "تنتهي في",
          "remaining time": "الوقت المتبقي",
          "extend ticket": "تمديد التذكرة",
          "sms": "رسالة نصية",
          "ticket(s)": "تذكرة/تذاكر",
          "time": "الوقت",
          "hour(S)": "ساعة/ساعات",
          "paid": "مدفوع",
          "aed": "د.أ",
          "active ticket(s)": "تذكرة/تذاكر نشطة",
          "recent ticket(s)": "تذكرة/تذاكر حديثة",
          "settings": "الإعدادات",
          "Parking Expiry Notification": "إشعار انتهاء الموقف",
          "Parking Renewal Notification": "إشعار تجديد الموقف",
          "Vibrate With Notification": "اهتزاز مع الإشعار",
          "Parking Renewal Before Expiry": "تجديد الموقف قبل انتهاء الصلاحية",
          "Notification Sound": "صوت الإشعار",
          "Language": "اللغة",
          "The vehicle has been added": "تم إضافة المركبة",
          "ADD VEHICLE": "إضافة مركبة",
          "plate source": "مصدر اللوحة",
          "plate type": "نوع اللوحة",
          "plate code": "رمز اللوحة",
          "plate number": "رقم اللوحة",
          "set as primary": "تعيين كلوحة أساسية",
          "update": "تحديث",
          "add": "إضافة",
          "MY VEHICLES": "مركباتي",
          "make\nprimary": "تعيين كلوحة أساسية",
          "add new vehicle": "إضافة مركبة جديدة",
          "edit": "تعديل",
          "delete": "حذف",
          "HOME": "الصفحة الرئيسية",
          "VEHICLES": "المركبات",
          "CONTACT US": "اتصل بنا",
          "SETTINGS": "الإعدادات",
          "The vehicle has been updated": "تم تحديث بيانات المركبة",
          "EMIRATES SMART PARKING": "مواقف الإمارات الذكية",
          "Add Vehicle": "إضافة مركبة",
          "Select an option": "اختر من القائمة",
          "All fields is required": "جميع الحقول مطلوبة",
          "Error": "خطأ",
          "City": "المدينة",
          "No data found..!": "لا يوجد بيانات..!",
          'Reply': "إرسال",
          "Opps...!": "للأسف...!",
          "Something wrong": "حصل شيء خطأ",
          "minutes": "دقائق"
        },
      };
}
